"""Public Python API for the headless Personal Knowledge Vault Kernel.

Desktop, web, and automation wrappers import this package instead of the
implementation namespace.  It deliberately re-exports only the stable Kernel
facade and its value contracts; no GUI framework is imported by this package.
"""

from src import __version__
from src.ai.chat_provider import ChatStreamEvent
from src.kernel import (
    ChatProvider,
    ChatProviderSettings,
    ChatStream,
    Config,
    ErrorCode,
    KernelChatSessions,
    KnowledgeKernel,
    LoggerSetup,
    PKVRuntimeError,
    PreviewIssue,
    PreviewOutcome,
    RetrievalIssue,
    SearchResponse,
    SearchResult,
    bootstrap_kernel,
    configure_kernel,
    describe_url_target,
    get_config,
    get_kernel,
    is_strict_chat_stream_event,
    is_strict_preview_outcome,
    is_strict_search_response,
    is_supported_chat_finish_reason,
    load_preview_with_store,
    open_user_file_nofollow,
    project_bootstrap_error,
    redact_url_credentials,
    reload_kernel,
    reset_kernel,
    sanitize_public_source_url,
    url_contains_credentials,
    validate_provider_base_url,
    validate_text_length,
    validate_url_security_result,
    WorkflowResult,
)
from src.runtime.errors import OperationStatus, StorageStage
from src.storage.coordinator import StorageOperationResult

__all__ = [
    "__version__",
    "ChatProvider",
    "ChatProviderSettings",
    "ChatStream",
    "ChatStreamEvent",
    "Config",
    "ErrorCode",
    "KernelChatSessions",
    "KnowledgeKernel",
    "LoggerSetup",
    "OperationStatus",
    "PKVRuntimeError",
    "PreviewIssue",
    "PreviewOutcome",
    "RetrievalIssue",
    "SearchResponse",
    "SearchResult",
    "StorageOperationResult",
    "StorageStage",
    "bootstrap_kernel",
    "configure_kernel",
    "describe_url_target",
    "get_config",
    "get_kernel",
    "is_strict_chat_stream_event",
    "is_strict_preview_outcome",
    "is_strict_search_response",
    "is_supported_chat_finish_reason",
    "load_preview_with_store",
    "open_user_file_nofollow",
    "project_bootstrap_error",
    "redact_url_credentials",
    "reload_kernel",
    "reset_kernel",
    "sanitize_public_source_url",
    "url_contains_credentials",
    "validate_provider_base_url",
    "validate_text_length",
    "validate_url_security_result",
    "WorkflowResult",
]
